ci: add GPG settings
FlowingCode/FontAwesomeIronIconset pull request #97
Opened 2023-08-16 19:50 UTC by javier-godoy

2023-08-16 19:51 UTC, mlopezFC requested changes
I think that there is a problem with a tag

2023-08-16 19:51 UTC, mlopezFC commented on pom.xml
> +		<profiles>
I think that this tag is wrong

2023-08-16 19:54 UTC, javier-godoy commented
> I think that there is a problem with a tag

Yes, I had fixed it locally but didn't realize the push didn't went through.

2023-08-17 18:21 UTC, paodb approved these changes

2023-08-28 13:24 UTC, mlopezFC approved these changes
LGTM

2023-08-28 13:24 UTC, merged